# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provider :aws do |aws, override|
    require 'yaml'
    settings = YAML.load(File.open("settings.yml").read)
    aws.access_key_id = settings["aws_access_key_id"]
    aws.secret_access_key = settings["aws_secret_access_key"]
    aws.keypair_name = settings["aws_keypair_name"]

    aws.ami = "ami-32015d5a" # flocker-only base
    #aws.ami = "ami-3cf8b154" # ubuntu 14.04
    #aws.instance_type = "m3.large"
    aws.instance_type = "c3.xlarge"

    override.vm.box = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
    #override.vm.box = "dummy"
    override.ssh.username = settings["remote_server_username"]
    override.ssh.private_key_path = settings["private_key_path"]
  end

  config.vm.define "node1" do |node1|
    node1.vm.provider :aws do |aws, override|
        aws.tags = {
            'Name' => 'flocker-powerstrip master',
        }
    end
  end
  config.vm.define "node2" do |node2|
    node2.vm.provider :aws do |aws, override|
        aws.tags = {
            'Name' => 'flocker-powerstrip minion',
        }
    end
  end

  config.vm.provision :shell, :path => "bootstrap.sh"
end
