#!/usr/bin/env python

"""
Create a docker container using the Docker Remote API over a local UNIX socket.
"""

from twisted.internet import reactor
from twisted.web.http_headers import Headers
import treq
import json
import sys
DOCKER = "http://unix=%2Fvar%2Frun%2Fdocker.sock"

def run_container(testfs):
    print "post create!"
    d = treq.post(DOCKER + "/v1.18/containers/create?name=%s" % (testfs,),
            data=json.dumps(dict(
                Image="busybox:latest",
                Cmd=["sh", "-c", "while true; do date > /data/file; sleep 1; done"],
                HostConfig=dict(Binds=["flocker/%s:/data" % (testfs,)]))),
            headers=Headers({"Content-Type": ["application/json"]}))
    d.addCallback(treq.json_content)
    def done_create(result):
        print "done create, result:", result
        container_id = result['Id'].encode("ascii")
        print "post start!"
        return treq.post(DOCKER + "/v1.18/containers/%s/start" % (container_id,),
            headers=Headers({"Content-Type": ["application/json"]}))
    d.addCallback(done_create)
    def done(result):
        reactor.stop()
    d.addBoth(done)
    return d

if __name__ == "__main__":
    reactor.callWhenRunning(run_container, sys.argv[1])
    reactor.run()
